# Form implementation generated from reading ui file 'gui_afpt.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(300, 350)
        MainWindow.setMinimumSize(QtCore.QSize(300, 350))
        MainWindow.setMaximumSize(QtCore.QSize(300, 350))
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_dodid = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_dodid.setObjectName("label_dodid")
        self.horizontalLayout.addWidget(self.label_dodid)
        self.input_dodid = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.input_dodid.setObjectName("input_dodid")
        self.horizontalLayout.addWidget(self.input_dodid)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_testresults = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_testresults.setObjectName("label_testresults")
        self.verticalLayout.addWidget(self.label_testresults)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_pushups = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_pushups.setObjectName("label_pushups")
        self.gridLayout_2.addWidget(self.label_pushups, 0, 0, 1, 1)
        self.spinbox_pushups = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinbox_pushups.setObjectName("spinbox_pushups")
        self.gridLayout_2.addWidget(self.spinbox_pushups, 0, 1, 1, 1)
        self.label_run_time = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_run_time.setObjectName("label_run_time")
        self.gridLayout_2.addWidget(self.label_run_time, 0, 2, 1, 1)
        self.timebox_input_run_time = QtWidgets.QTimeEdit(parent=self.centralwidget)
        self.timebox_input_run_time.setObjectName("timebox_input_run_time")
        self.gridLayout_2.addWidget(self.timebox_input_run_time, 0, 3, 1, 1)
        self.label_situps = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_situps.setObjectName("label_situps")
        self.gridLayout_2.addWidget(self.label_situps, 1, 0, 1, 1)
        self.spinbox_situps = QtWidgets.QSpinBox(parent=self.centralwidget)
        self.spinbox_situps.setObjectName("spinbox_situps")
        self.gridLayout_2.addWidget(self.spinbox_situps, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_validation = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_validation.setObjectName("label_validation")
        self.gridLayout.addWidget(self.label_validation, 0, 0, 1, 1)
        self.button_submit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.button_submit.setObjectName("button_submit")
        self.gridLayout.addWidget(self.button_submit, 1, 0, 1, 1)
        self.label_score = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_score.setObjectName("label_score")
        self.gridLayout.addWidget(self.label_score, 2, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 2, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "AF PT"))
        self.label_dodid.setText(_translate("MainWindow", "DoD ID:"))
        self.label_testresults.setText(_translate("MainWindow", "PT Test Results"))
        self.label_pushups.setText(_translate("MainWindow", "Pushups:"))
        self.label_run_time.setText(_translate("MainWindow", "1.5 Mile Time:"))
        self.label_situps.setText(_translate("MainWindow", "Situps:"))
        self.label_validation.setText(_translate("MainWindow", "Press submit for score"))
        self.button_submit.setText(_translate("MainWindow", "Submit"))
        self.label_score.setText(_translate("MainWindow", "Your Score: "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
